# Durability config file
  # Whether or not the player (after join) has this plugin enabled
  # Will be overwritten if the player chose not to enable this plugin (by command /duwoff|on)
  enabled-by-default: true