 name: Durability Warner
 version: 0.4
 description: Durability Warner by Paco

 author: Paco
 authors: [Paco]
 website: http://paskl.de
 
 main: de.paskl.durability.Main

 commands:
   duw:
     description: Durability Warner Command.
     aliases: [durabilitywarner]
     usage: /<command> [0|off|1|on]