 name: Durability Warner
 version: 0.2
 description: Durability Warner by Paco

 author: Paco
 authors: [Paco]
 website: http://paskl.de
 
 main: de.paskl.durability.Main

 commands:
   duwon:
     description: Enabled the low durability warning for you.
     aliases: [durabilitywarner_disable, durabilitywarner-disable]
     usage: /<command>
   duwoff:
        description: Disabled the low durability warning for you.
        aliases: [durabilitywarner_enable, durabilitywarner-enable]
        usage: /<command>